/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Priscila Lunarejo
 */
public class FrmInsumos extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmInsumos
     */
    public FrmInsumos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblRegistroInsumos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jbtnRegistrar = new javax.swing.JButton();
        jbtnActualizar = new javax.swing.JButton();
        jbtnConsultar = new javax.swing.JButton();
        jbtnEliminar = new javax.swing.JButton();
        jtxtIdinsumos = new javax.swing.JTextField();
        jcbxNombres = new javax.swing.JComboBox<>();
        jdtchssFechainsgreso = new com.toedter.calendar.JDateChooser();
        jtxtStock = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jlblCantidadRegistros = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtblRegistroInsumos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblRegistroInsumos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 500, 260));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTRO DE LOS INSUMOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei UI", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnRegistrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnRegistrar.setText("REGISTRAR");
        jPanel1.add(jbtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 140, 50));

        jbtnActualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnActualizar.setText("ACTUALIZAR");
        jPanel1.add(jbtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 140, 50));

        jbtnConsultar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnConsultar.setText("CONSULTAR");
        jPanel1.add(jbtnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 140, 50));

        jbtnEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnEliminar.setText("ELIMINAR");
        jPanel1.add(jbtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 140, 50));

        jtxtIdinsumos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID INSUMOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel1.add(jtxtIdinsumos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 110, 50));

        jcbxNombres.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECCIONE--", "HAN TAG", "CIERRES", "HILOS", "PLACAS", "REMACHES", "LLAVEROS", "BOTONES METÁLICOS", "BOTONES DE PLÁSTICO", "CORREAS", "ETIQUETA DE PRETINA", "ETIQUETA DE TALLA", "ETIQUETA DE INSTRUCCIÓN", "CINTAS DE PRETINA", "HEBILLAS", "BOLSAS", "" }));
        jcbxNombres.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NOMBRES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel1.add(jcbxNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 190, 50));

        jdtchssFechainsgreso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FECHA INGRESO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel1.add(jdtchssFechainsgreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 180, 50));

        jtxtStock.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STOCK", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel1.add(jtxtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 120, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 350, 310));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 30)); // NOI18N
        jLabel2.setText("LISTA DE LOS INSUMOS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        jlblCantidadRegistros.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblCantidadRegistros.setText("Cantidad de registros: ");
        getContentPane().add(jlblCantidadRegistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtnActualizar;
    public javax.swing.JButton jbtnConsultar;
    public javax.swing.JButton jbtnEliminar;
    public javax.swing.JButton jbtnRegistrar;
    public javax.swing.JComboBox<String> jcbxNombres;
    public com.toedter.calendar.JDateChooser jdtchssFechainsgreso;
    public javax.swing.JLabel jlblCantidadRegistros;
    public javax.swing.JTable jtblRegistroInsumos;
    public javax.swing.JTextField jtxtIdinsumos;
    public javax.swing.JTextField jtxtStock;
    // End of variables declaration//GEN-END:variables
}
