/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Priscila Lunarejo
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdscpContenedor = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mitemRegistrarCliente = new javax.swing.JMenuItem();
        mitemRegistrarEmpleado = new javax.swing.JMenuItem();
        mitemRegistrarProductos = new javax.swing.JMenuItem();
        mitemRegistrarProveedores = new javax.swing.JMenuItem();
        mitemRegistrarInsumos = new javax.swing.JMenuItem();
        mitemRegistroVentas = new javax.swing.JMenuItem();
        mitemRegistroEnvio = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mitemPagosVenta = new javax.swing.JMenuItem();
        miitemPagoEnvio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdscpContenedor.setBackground(new java.awt.Color(204, 204, 255));
        jdscpContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu1.setText("Registros");

        mitemRegistrarCliente.setText("Registro Cliente");
        jMenu1.add(mitemRegistrarCliente);

        mitemRegistrarEmpleado.setText("Registro Empleado");
        jMenu1.add(mitemRegistrarEmpleado);

        mitemRegistrarProductos.setText("Registro Productos");
        jMenu1.add(mitemRegistrarProductos);

        mitemRegistrarProveedores.setText("Registro Proveedores");
        jMenu1.add(mitemRegistrarProveedores);

        mitemRegistrarInsumos.setText("Registro Insumos");
        jMenu1.add(mitemRegistrarInsumos);

        mitemRegistroVentas.setText("Registro Ventas");
        jMenu1.add(mitemRegistroVentas);

        mitemRegistroEnvio.setText("Registro Envio");
        jMenu1.add(mitemRegistroEnvio);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pagos");

        mitemPagosVenta.setText("Pagos Venta");
        jMenu2.add(mitemPagosVenta);

        miitemPagoEnvio.setText("Pagos Envio");
        jMenu2.add(miitemPagoEnvio);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdscpContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdscpContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JDesktopPane jdscpContenedor;
    public javax.swing.JMenuItem miitemPagoEnvio;
    public javax.swing.JMenuItem mitemPagosVenta;
    public javax.swing.JMenuItem mitemRegistrarCliente;
    public javax.swing.JMenuItem mitemRegistrarEmpleado;
    public javax.swing.JMenuItem mitemRegistrarInsumos;
    public javax.swing.JMenuItem mitemRegistrarProductos;
    public javax.swing.JMenuItem mitemRegistrarProveedores;
    public javax.swing.JMenuItem mitemRegistroEnvio;
    public javax.swing.JMenuItem mitemRegistroVentas;
    // End of variables declaration//GEN-END:variables
}
