/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Priscila Lunarejo
 */
public class FrmProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmProducto
     */
    public FrmProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblRegistroProd = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jbtnRegistrar = new javax.swing.JButton();
        jbtnActualizar = new javax.swing.JButton();
        jbtnConsultar = new javax.swing.JButton();
        jbtnEliminar = new javax.swing.JButton();
        jtxtStock = new javax.swing.JTextField();
        jtxtIdproducto = new javax.swing.JTextField();
        jtxtPrecio = new javax.swing.JTextField();
        jtxtdescripcion = new javax.swing.JTextField();
        jdtchssFecha = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jlblCantidadregistros = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtblRegistroProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblRegistroProd);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 590, 320));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTRO DE LOS PRODUCTOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei UI", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnRegistrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnRegistrar.setText("REGISTRAR");
        jPanel1.add(jbtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 150, 60));

        jbtnActualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnActualizar.setText("ACTUALIZAR");
        jPanel1.add(jbtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 150, 60));

        jbtnConsultar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnConsultar.setText("CONSULTAR");
        jPanel1.add(jbtnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 150, 60));

        jbtnEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnEliminar.setText("ELIMINAR");
        jPanel1.add(jbtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 150, 60));

        jtxtStock.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STOCK", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel1.add(jtxtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, 50));

        jtxtIdproducto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID PRODUCTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel1.add(jtxtIdproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 110, 50));

        jtxtPrecio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PRECIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel1.add(jtxtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 140, 50));

        jtxtdescripcion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DESCRIPCION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel1.add(jtxtdescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 200, 50));

        jdtchssFecha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FECHA INGRESO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel1.add(jdtchssFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 170, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 340, 400));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 30)); // NOI18N
        jLabel2.setText("LISTA DE LOS PRODUCTOS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, -1, -1));

        jlblCantidadregistros.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblCantidadregistros.setText("Cantidad de registros: ");
        getContentPane().add(jlblCantidadregistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 470, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtnActualizar;
    public javax.swing.JButton jbtnConsultar;
    public javax.swing.JButton jbtnEliminar;
    public javax.swing.JButton jbtnRegistrar;
    public com.toedter.calendar.JDateChooser jdtchssFecha;
    public javax.swing.JLabel jlblCantidadregistros;
    public javax.swing.JTable jtblRegistroProd;
    public javax.swing.JTextField jtxtIdproducto;
    public javax.swing.JTextField jtxtPrecio;
    public javax.swing.JTextField jtxtStock;
    public javax.swing.JTextField jtxtdescripcion;
    // End of variables declaration//GEN-END:variables
}
